### ISSUE TITLE
T1 - Versión de d3

### ISSUE THREAD

**Issue by Geeermy** [PUC-Infovis/syllabus-2018#10]
¡Hola!

Por alguna razón estaba enfocado en trabajar con la versión v5 de d3, pero ahora me puse a revisar y no aparece como requisito (no lo vi ni por correo, ni enunciado, ni una _issue_).

En resumen: ¿puedo usar v3 o v4 también para la tarea? (especificándolo en el informe, por supuesto).

¡Gracias! 🐱

**Comment by Geeermy** [comment]
**PD:** Si es que estaba en alguna parte y se me pasó, me disculpo desde ya. 😞

**Comment by fdoflorenzano** [comment]
Hola, como se dijo en **ayudantía**, no exigiremos una versión de d3 para esta tarea. Pero si recomendamos utilizar su última versión, ya que será la utilizada en ayudantía y en las futuras tareas.  Deben especificar que versión utilizan, si no es la última.

**Comment by Geeermy** [comment]
Ups! No pude asistir a ella. 😢

¡Gracias! 🐈
