### ISSUE TITLE
Archivos de prueba

### ISSUE THREAD

**Issue by ifcarrera** [PUC-Infovis/syllabus-2018#11]
Hola, 
al momento de que ustedes prueben nuestras tareas, ¿usarán los mismos archivos que nos pasaron u otros?. En caso de que ocupen otros, ¿qué formatos tendrán o qué tan diferentes serán de los que nos entregaron?
Saludos

**Comment by fdoflorenzano** [comment]
Hola, 
Buena pregunta. No modificaremos los archivos de input para la corrección.
Saludos.
