### ISSUE TITLE
T01 Presentacion de Resultados

### ISSUE THREAD

**Issue by Sforrego** [PUC-Infovis/syllabus-2018#15]
Tengo una duda con el punto 3 y 4 donde habla sobre importar el svg y mostrar el resultado sobre un elemento svg, a que se refiere mostrar el resultado sobre un elemento svg? 
puedo simplemente importar el svg con <img src='imagen.svg'/> ?

Tambien nos piden que el texto este centrado y justificado, pero el text-align es el mismo atributo para ambos, debe estar centrado o justificado?

**Comment by BeaGaete** [comment]
Tengo la misma duda

**Comment by fdoflorenzano** [comment]
Hola,
Sobre los puntos 3 y 4, como se habrán dado cuenta, el 3 se refiere a lo realizado con Python y el 4 a lo realizado con D3. Lo realizado con Python resulta en un archivo SVG que hay que importar al informe de resultados, por otra parte, lo realizado con D3 es JavaScript y se ejecuta en el archivo HTML. Como hemos visto en las ayudantías de D3, los gráficos los armamos dentro de un elemento HTML llamado `<svg>`, a ese se refiere.

**Comment by Sforrego** [comment]
Me quedo clarisimo, muchas gracias!
