### ISSUE TITLE
proyecto datos

### ISSUE THREAD

**Issue by jvlara** [PUC-Infovis/syllabus-2018#23]
El dataset elegido para el proyecto se puede trabajar primero en python y luego visualizarlo ?

**Comment by Hernan4444** [comment]
Hola, si se puede.

Saludos ✌️

**Comment by BeaGaete** [comment]
Se puede utilizar bases de datos a través de python?

**Comment by Hernan4444** [comment]
Hola, puedes detallar un poco más la pregunta, no entiendo bien a que te refieres con utilizar bases de datos a través de python.

**Comment by BeaGaete** [comment]
Nuestro dataset tiene varios archivos .csv y necesitamos hacer JOIN, me gustaría usar sqlite3 en python para hacerlo como parte del preprocesamiento de datos

**Comment by BeaGaete** [comment]
yaaaa!! muchas gracias!!!
