### ISSUE TITLE
slides presentación

### ISSUE THREAD

**Issue by francisca1** [PUC-Infovis/syllabus-2018#25]
En las intrucciones para las slides de la presentación, se mencionan que deben estar los pasos a seguir en el desarrollo. A que se refiere esto ? , a lo que queda por avanzar en el proyecto ?

**Comment by Hernan4444** [comment]
Efectivamente, tienen que indicar que es lo que les que tienen pensado hacer a continuación para terminar el proyecto

Saludos ✌️
