### ISSUE TITLE
duda tarea 2 barchart

### ISSUE THREAD

**Issue by francisca1** [PUC-Infovis/syllabus-2018#26]
si hago doble click en un nodo(nodo1) y luego en otro(nodo2), en el barchart se deben presentar el nodo 1 y sus vecinos y luego agregar el nodo 2 y sus vecinos? o cambiar desde nodo1 y sus vecinos a nodo2 y sus vecinos?

**Comment by Hernan4444** [comment]
Hola,
Es lo segundo, primero el nodo 1 y vecinos, para luego cambiar al nodo 2 y sus vecinos.

Saludos :v:
