### ISSUE TITLE
[Tarea 2]: Click en nodo

### ISSUE THREAD

**Issue by ifcarrera** [PUC-Infovis/syllabus-2018#27]
Hola!

No entiendo esto:

> Al arrastrar un nodo, su posición debe quedar fija incluso si se deja de arrastrar.
Sólo si se hace clic (i.e. click) sobre el nodo, se libera su posición.

¿A qué se refiere con que su posición debe quedar fija y que se libere al hacer click?

Saludos

**Comment by fdoflorenzano** [comment]
¡Hola!
Como tratamos con un diagrama de nodos y enlaces, se da por entendido que las posiciones de estos nodos se actualizan constantemente, por la cercanía con otros nodos, y es posible manipularlos para ordenarlos a deseo del usuario. Entre esas manipulaciones, está el 'arrastrar' cuyo efecto es mover un nodo y dejarlo en la última posición del arrastre, sin ser afectado por la presencia de nodos cercanos. La otra manipulación, es permitir des-fijar dicho nodo que quedó fijo, y eso se hace mediante un clic simple.
Espero se entienda lo pedido.
Saludos.
