### ISSUE TITLE
Tarea 3 manejo de identidades

### ISSUE THREAD

**Issue by francisca1** [PUC-Infovis/syllabus-2018#31]
En el enunciado de la tarea dice que queda a nuestro criterio el manejo de la cantidad de identidades en las películas, esto quiere decir que se podría aplicar alguna reducción?.
Gracias.

**Comment by fdoflorenzano** [comment]
Hola, así es, una alternativa es reducir el número de personajes que se muestres. Ahora, recuerda que tanto el número que se elija para mostrar debe estar justificado, como la misma decisión de reducir el número de personajes. Exploren alternativas a solo reducir.
Saludos.
