### ISSUE TITLE
Modificar datos t3

### ISSUE THREAD

**Issue by behrmann97** [PUC-Infovis/syllabus-2018#32]
Hola!, 
¿Se pueden modificar los datos de la tarea? No agregar  o quitar filas, sino utilizar python o algo para agregar una columna de utilidad, es decir, agregarle un parametro.

**Comment by fdoflorenzano** [comment]
Hola, buena pregunta. Pueden hacer preprocesamiento previo (ya sea en Python como en JS), de hacerlo, compartan el código en su tarea y expliquen en su informe que hicieron. Y como dices, los valores originales no debiesen mutar, pero pueden calcular a partir de ellos lo que estimen necesario para facilitar su manejo en D3.
Saludos.
