### ISSUE TITLE
Ordenar gráficos

### ISSUE THREAD

**Issue by csolguin** [PUC-Infovis/syllabus-2018#33]
En el enunciado cuando dice:
``` La visualización debe incluir la opción de ordenar los gráﬁcos en dos criterios distintos ```
Se refiere a que debemos ocupar si o si un < select > o puedo aplicar 2 botones o tabs que actualizen la visualización para los criterios correspondientes
Saludos ✌️ y gracias de antemano 😀

**Comment by Hernan4444** [comment]
Hola, queda totalmente a tu criterio como implementar lo solicitado, puede ser con select, con tabs, botones, como tu quieras.

Saludos ✌️
