### ISSUE TITLE
Idyll [Tarea 3]

### ISSUE THREAD

**Issue by csolguin** [PUC-Infovis/syllabus-2018#34]
¿Esta permitido ocupar Idyll en la tarea 3? (básicamente para el hover)
Saludos :sweat_smile:

**Comment by Hernan4444** [comment]
Hola @csolguin,

Si puedes ocupar Idyll 👍 , pero la idea inicial era que lo hicieran sin ello para que utilizaran sus conocimientos en D3 para enfrentar el requerimiento del *hover*, pero con el apoyo de la solución en Idyll. No obstante, como dije inicialmente, si puedes ocupar Idyll para poder tener el hover implementado. Solo ten cuidado que un componente en D3 con Idyll tiene ligeras diferencias con un visualización en D3 creado sin Idyll, para que veas que todo lo que tengas funcione correctamente con Idyll c:

Saludos ✌️

**Comment by csolguin** [comment]
Estimado, es permitido a pesar de tener dependencias con d3fc?
``` "d3", "d3fc", "idyll", "idyll-d3-component" ```
Ya que me dijeron que estaba **prohibido** ocupar dicha coleccion de modulos (d3fc)
Saludos  ✌️

**Comment by Hernan4444** [comment]
Si, está permitido, porque las cosas que ocupa Idyll de d3fc son para otros objetivos, pero lo que tu harás de Idyll (un idyll-d3-component como el de la ayudantía) no tendrá ningún uso de "d3fc".
