### ISSUE TITLE
Subir clase 12 Reducir

### ISSUE THREAD

**Issue by lukassr** [PUC-Infovis/syllabus-2018#36]
Hola,

Podrían subir la clase 12 de reduce al syllabus, por favor? Esta solo en el siding y el ~~magnífico~~ servidor de ingeniería está a 1 mbps.

Gracias 🙂

**Comment by Hernan4444** [comment]
@lukassr acabo de subirla, gracias por notar que no lo estaba.

Saludos ✌️
