### ISSUE TITLE
Inscripción de grupos de proyecto

### ISSUE THREAD

**Issue by fdoflorenzano** [PUC-Infovis/syllabus-2018#6]
Utilicen esta _issue_ para publicar sus grupos de proyecto para trabajar durante el semestre. Cada grupo debe estar formado por **tres integrantes** y debe tener un **nombre de grupo**, que usarán en sus **repositorios** asignados. En caso de no tener grupo o falta de un integrante, pueden publicar aquí su situación para comunicarse con posibles compañeros.

**DEADLINE**: 31 de agosto, 23:59.
**EXTENSIÓN**: 1 de septiembre, 23:59.

**Comment by RodrigoBocazG** [comment]
Guadalupe García
Rodrigo Bocaz
Alexis Cerna

**Comment by Geeermy** [comment]
Germán Contreras 🎉
Lukas Svicarovic 🎆
Ivania Yovanovic 🎊

**Comment by IchottMano** [comment]
Matías Gabler
Pablo Olea
Ricardo Schilling

**Comment by sricke** [comment]
Sebastian Ricke
Jose Pablo Dominguez
Guillermo Espinoza

**Comment by Dunkan1** [comment]
Hola, a nuestro grupo le falta un integrante, si quieren ser con nosotros
escriban a dntorres1@uc.cl 

Saludos.

**Comment by Diiru** [comment]
Cristóbal Eyzaguirre
Rolf Skog
Diego Iruretagoyena

Nombre grupo: Hattrick

**Comment by VinceValence** [comment]
**Nombre**: InfoVisto

**Integrantes**:

- Maximiliano Friedl
- Thomas Reisenegger
- Vicente Valencia

**Comment by andresfdezc** [comment]
**tamara-and-the-munzners**:
- Manuel Cartagena
- Andrés Fernández
- Daniela Flores

**Comment by jisilvamc** [comment]
Pink Panthers 4ever:
Juan Ignacio Silva
Rolf Sommer
Ambrosio Valdés

**Comment by Dunkan1** [comment]
**LosLeePapers**
- Cristobal Muñoz
- Cesar Olguin
- Dunkan Torres

**Comment by regarin** [comment]
Nombre del grupo: Bostock's Boys

- Eugenio Herrera
- Joaquín Sáez
- Rafael Garín

**Comment by cotiravanal** [comment]
Gianfranco Giglio
Martín Ramirez 
Constanza Ravanal

Nombre grupo: abc

**Comment by Javierdr** [comment]
Nos falta un integrante. Si hay alguien solo me puede mandar un mail a jidreves@uc.cl o puede comentar aqui mismo. 
**Nombre:** Visualización de desinformación.
**Integrantes:** 
- Isaac Carrera
- Javier Dreves

**Comment by evd995** [comment]
Nombre: Squanch
Integrantes:
- Valentina Muñoz
- Genaro Laymuns
- Esteban Villalobos

**Comment by Arios16** [comment]
Nombre: ELI11
Integrantes:
- Antonio López
- Vicente Errázuriz
- Andrés Ríos

**Comment by jvlara** [comment]
Nombre: Franjoiv
Integrantes:
- José Lara 
- Iván Wolf
- Francisca Rebolledo

**Comment by sfga** [comment]
Buscamos un(a) integrante. Si quieres unirte (y mejorar el nombre del grupo), envía un mail a jpchacon@uc.cl o sfgarces@uc.cl o deja un comentario en esta issue.

**Nombre del grupo**: "Denis Danis"

**Integrantes**:
- Juan Pablo Chacón
- Simón Garcés

**Comment by BeaGaete** [comment]
Sebastián Orrego
Beatriz Gaete
