### ISSUE TITLE
T1 - Dudas

### ISSUE THREAD

**Issue by eiherrera** [PUC-Infovis/syllabus-2018#7]
Hola! Tengo algunas dudas respecto a la tarea 1:

* No me he topado con que algún alumno haya rendido un ramo en más de un semestre. ¿Puedo asumir que esto es siempre así?

* No me queda claro cómo deben ser los archivos por hacer del ítem 1.2, ¿éstos son aparte de los que hay que hacer por los ítems 2 y 3? En caso de ser así, ¿los archivos solo deben contener los promedios generales por ramo por semestre, o también deben contener el promedio final de cada alumno por semestre?

**Comment by Hernan4444** [comment]
Hola,

1) Para esta tarea, esa información no es relevante, ya que interesan los promedios por semestre, no de cada alumno. De todas formas, si puedes asumir eso.
2) Así es, en el 1.2 generas los datos necesarios para poder construir los gráficos del ítem 2 y 3. El formato que tenga el archivo queda a tu criterio mientras presente el preprocesamiento adecuado. La intención es dejar toda la responsabilidad de preprocesamiento al 1.2 y que en la parte de visualización debería haber un mínimo de procesamiento, debe generar los gráficos.

Saludos ✌️
