### ISSUE TITLE
Problema pandas y tildes

### ISSUE THREAD

**Issue by jgespinosa10** [PUC-Infovis/syllabus-2018#9]
Pandas no permite tildes en el nombre de los archivos, podrían cambiarle el nombre? Que se puede hacer?

**Comment by fdoflorenzano** [comment]
Hola, 
Puedes cambiarle tu localmente los nombres para que se carguen correctamente. Este es un error que varía entre sistemas, por lo que no olvides mencionar en tu informe o en el mismo código que alteraste los nombres de los archivos base. Así lo consideraremos durante la corrección.

Saludos.
